# YOLOv5 ğŸš€ by Ultralytics, GPL-3.0 license

name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            è¯¶ï¼Ÿæˆ‘ç«Ÿç„¶è¿˜èƒ½æ”¶åˆ°PRï¼Ÿ
            ğŸ‘‹ ä½ å¥½ @${{ github.actor }}, éå¸¸æ„Ÿè°¢æäº¤ ğŸš€ PR!
            æœ¬repoæ˜¯forkè‡ªåŸç‰ˆyolov5å·¥ç¨‹ï¼Œä»£ç æ–¹é¢çš„PRè¯·æäº¤è‡³å®˜æ–¹ä»“åº“åœ°å€ï¼ŒREADMEçš„ç›¸å…³PRæˆ‘ä¼šå®¡æŸ¥æ— è¯¯åmerge
          issue-message: |
            ğŸ‘‹ ä½ å¥½ @${{ github.actor }}, å¦‚æœ‰ä»»ä½•é—®é¢˜ï¼Œè¯·é¦–å…ˆæ£€æŸ¥ä½ çš„è¿è¡ŒæŒ‡ä»¤æœ‰æ²¡æœ‰é—®é¢˜ï¼Œå¦‚æœæŒ‡ä»¤æ²¡æœ‰é—®é¢˜ï¼Œè¯·å°è¯•æ›´æ–°ä½œè€…ä»“åº“çš„æœ€æ–°ä»£ç ï¼š
            ```bash
              # å¦‚æœæ²¡ä¸‹è½½å®˜æ–¹ä»£ç 
              $ git clone https://github.com/ultralytics/yolov5.git
              $ cd yolov5
              $ pip install -r requirements.txt
            ```
            ```bash
              # å¦‚æœå·²ä¸‹è½½å®˜æ–¹ä»£ç 
              $ cd yolov5
              $ git reset --hard
              $ git pull
              $ pip install -r requirements.txt
            ```
            æ›´å¤šè¯·å‚è€ƒâ­ï¸[è‹±æ–‡å®˜æ–¹æ•™ç¨‹](https://github.com/ultralytics/yolov5/wiki#tutorials)

            ## ä¾èµ–

            Pythonç‰ˆæœ¬3.6æˆ–æ›´é«˜ï¼Œpythonä¾èµ–åº“éƒ½åœ¨[requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) é‡Œé¢ï¼Œç›´æ¥`pip install -r requirements.txt`å³å¯ã€‚
            å¦‚æœä½ ä½¿ç”¨Windowsçš„è¯ï¼Œå°½é‡ä½¿ç”¨CUDA10.2å’Œå¯¹åº”ç‰ˆæœ¬çš„pytorchï¼ŒCUDA11+ä¼šæœ‰äº›è®¸é—®é¢˜ã€‚

            ## ç¯å¢ƒ
            ä¸‹é¢æ˜¯å·²ç»é…ç½®å¥½ç¯å¢ƒçš„å…è´¹GPUè®­ç»ƒç¯å¢ƒï¼š
            - **Google Colab and Kaggle** : <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
            - **Google Cloud** : [GCP å¿«é€Ÿä¸Šæ‰‹æ•™ç¨‹](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
            - **Amazon** Deep Learning AMI. See [AWS å¿«é€Ÿä¸Šæ‰‹æ•™ç¨‹](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
            - **Docker Image**. [Docker å¿«é€Ÿä¸Šæ‰‹æ•™ç¨‹](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

